dist: trusty
language: node_js
node_js: '6'

addons:
  apt:
    sources: google-chrome
    packages: google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - node --version
  - npm --version
  - bower --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - npm install --no-optional

install:
  - npm install
  - bower install

script:
  - npm test
  - node_modules/.bin/snazzy
