language: node_js
node_js: '6'

cache:
  directories:
    - node_modules

before_install:
  - node --version
  - npm --version
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs@1.9.19
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test
  - node_modules/.bin/snazzy
